import pygame
from game_field import *
from screen import *

GREEN = (0, 200, 0)
SCREEN_WIDTH = 1000
SCREEN_LENGTH = 500
BUSH_SIZE = (50, 50)
SQUARE = 20
FLAG_WIDTH = 4 * SQUARE
FLAG_LENGTH = 3 * SQUARE
SOLDIER_WIDTH = 2 * SQUARE
SOLDIER_LENGTH = 4 * SQUARE
BOMB_WIDTH = 3 * SQUARE
BOMB_LENGHT = SQUARE
BOMB_SIZE = (BOMB_WIDTH, BOMB_LENGHT)